/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameResult {
  'game' : string,
  'user' : Principal,
  'timestamp' : Time,
  'amountWon' : bigint,
}
export interface Profile {
  'username' : string,
  'balance' : bigint,
  'totalWon' : bigint,
  'phone' : string,
}
export type Time = bigint;
export interface Transaction {
  'description' : string,
  'timestamp' : Time,
  'balanceAfter' : bigint,
  'amount' : bigint,
}
export interface _SERVICE {
  'addCoins' : ActorMethod<[bigint], undefined>,
  'getBalance' : ActorMethod<[], bigint>,
  'getRecentWins' : ActorMethod<[], Array<GameResult>>,
  'getTopPlayers' : ActorMethod<[], Array<Profile>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'register' : ActorMethod<[string, string], undefined>,
  'requestDeposit' : ActorMethod<[bigint, string], undefined>,
  'submitGameResult' : ActorMethod<[string, boolean, bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];