/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const GameResult = IDL.Record({
  'game' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amountWon' : IDL.Nat,
});
export const Profile = IDL.Record({
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'totalWon' : IDL.Nat,
  'phone' : IDL.Text,
});
export const Transaction = IDL.Record({
  'description' : IDL.Text,
  'timestamp' : Time,
  'balanceAfter' : IDL.Nat,
  'amount' : IDL.Int,
});

export const idlService = IDL.Service({
  'addCoins' : IDL.Func([IDL.Nat], [], []),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getRecentWins' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
  'getTopPlayers' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'requestDeposit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'submitGameResult' : IDL.Func([IDL.Text, IDL.Bool, IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const GameResult = IDL.Record({
    'game' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amountWon' : IDL.Nat,
  });
  const Profile = IDL.Record({
    'username' : IDL.Text,
    'balance' : IDL.Nat,
    'totalWon' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'description' : IDL.Text,
    'timestamp' : Time,
    'balanceAfter' : IDL.Nat,
    'amount' : IDL.Int,
  });
  
  return IDL.Service({
    'addCoins' : IDL.Func([IDL.Nat], [], []),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getRecentWins' : IDL.Func([], [IDL.Vec(GameResult)], ['query']),
    'getTopPlayers' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'requestDeposit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'submitGameResult' : IDL.Func([IDL.Text, IDL.Bool, IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };